channels:
- conda-forge
dependencies:
- python=3.10.11
- pip<=23.0.1
- pip:
  - mlflow==2.6.0
  - cloudpickle==2.2.1
  - numpy==1.24.3
  - psutil==5.9.0
  - scikit-learn==1.0.2
  - scipy==1.10.1
  - typing-extensions==4.5.0
name: mlflow-env
